name: Deploy to Github  Pages
on:
  workflow_dispatch:
  push:
    branches: "main"
permissions:
    contents: read
    pages: write
    id-token: write
concurrency:
    group: "pages"
    cancel-in-progress: true
jobs:
    build:
      environment: production
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
          working-directory: ./app
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install dependencies
          run: npm ci
        - name: Build
          run: npm run build
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v2.0.0
          with:
            path: ./app/dist
            name: artifact
    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Configure GitHub Pages
          uses: actions/configure-pages@v3.0.6
          id: pages
        - name: Deploy Github Pages site
          id: deployment
          uses: actions/deploy-pages@v1.2.9
          with:
            artifact_name: artifact